# O propósito desse Dockerfile é facilitar a execução dos exemplos originais do livro "Entendendo Algoritmos"
# O utilizo para não precisar instalar localmente na minha máquina o Python 2.7

FROM python:2.7

WORKDIR /usr/src/app

COPY . .

CMD ["python", "./pilha_recursao.py"]